### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by StrangeReseach100PK** [ameraner/dsen2-cr#9]
Hi , Is it possible to deploy the model?
We always giving triplet data,But how can we will predict only on Real test data without Groundtruth?
Could you please suggest me on this.
Thank you

**Comment by ameraner** [comment]
Hi @StrangeReseach100PK , of course it's possible to use the model in prediction mode, i.e. with only the cloudy and SAR images as input. You can enter this mode using `python dsen2cr_main.py --predict path/to/checkpoint.h5`. Please also check [the according code](https://github.com/ameraner/dsen2-cr/blob/main/Code/dsen2cr_main.py) for the configuration setup.

**Comment by StrangeReseach100PK** [comment]
Thank you @ameraner ,  should we need to provide csv file always?

**Comment by ameraner** [comment]
Yes, that's still a required input, to let the model know where to find the input images

**Comment by GKG1312** [comment]
Hi @ameraner ,
I am trying to use this method but need help giving input for prediction. From the above comments, I got that we have to give our real image path after giving it the proper name as the data has when the model is trained. But I would like some clarification about the shape of the data since I am using only images for a single day. Will the shape of the file be (13, width, height), or do I have to crop images to 128x128 size?
Also, will it be possible if I want to use this model only with a sentinel-2 image? I found that there is a saved weight for only sentinel-2 data also.
Can you help me with these?

PS: I am new to this field, so my doubts may be some silly things I am missing.

Thank you.

**Comment by ameraner** [comment]
Hi @GKG1312 , thank you for your message!
The images do not need to be cropped at prediction time, you can define the input/output size based on how much your system can cope with in terms of (GPU) memory. For my predictions I was using something like 1000x1000 px and then assembling the full image out those tiles.
And yes, you should be able to run the model without S1 input by setting the configuration variable accordingly around here https://github.com/ameraner/dsen2-cr/blob/59e81ae0d013bcae992d078e92a1175cc4cbf257/Code/dsen2cr_main.py#L33

**Comment by ameraner** [comment]
Closing this as solved, feel free to reopen if you have any more issues/questions :)
